name: Rust
on:
  push:
    branches: [ "main" ]
    paths:
      - src/**/*
      - Cargo.toml
      - .github/workflows/**/*
  pull_request:
    branches: [ "main" ]
    paths:
      - src/**/*
      - Cargo.toml
      - .github/workflows/**/*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Run tests
        run: cargo test --verbose
      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: Check compilation for wasm32-unknown-unknown
        run: cargo check --target wasm32-unknown-unknown --tests --verbose

  publish:
    name: Publish (crates.io)
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: cargo-release cache restore
        id: cargo_release_cache_restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.cargo/bin/cargo-release
          key: ${{ runner.os }}-cargo-release

      - run: cargo install cargo-release
        if: steps.cargo_release_cache_restore.outputs.cache-hit != 'true'

      - name: cargo-release cache save
        id: cargo_release_cache_save
        uses: actions/cache/save@v4
        if: always() && steps.cargo_release_cache_restore.outputs.cache-hit != 'true'
        with:
          path: ~/.cargo/bin/cargo-release
          key: ${{ runner.os }}-cargo-release

      - name: cargo login
        run: |-
          echo "${{ secrets.CRATES_IO_API_TOKEN }}" | cargo login

      - name: "cargo publish"
        run: |-
          cargo publish --no-verify
